project_id = "project-lemonade"

[functions.instagram-import]
verify_jwt = false

[functions.place-search]
verify_jwt = false

[functions.place-locations]
verify_jwt = false

[functions.plan-sharing]
verify_jwt = false

[functions.shared-plan]
verify_jwt = false
