import assert from 'node:assert/strict';
import test from 'node:test';
import { normalizePlanTitle, sortPlans, planTransition, membershipFeedback, pickPlanPlace, planPlaces, type DiningPlan } from '../src/types/dining-plan';
import { buildMapUrl, validStoredMapUrl } from '../src/services/map-handoff';
import { mapPlanRow, PlansRepository, PlanStorageError } from '../src/repositories/plans/plans-repository';
import { createPlaceDataExport } from '../src/services/export/place-data-export';
import { hooks, load, tick, flatten, rn, theme } from './helpers/component-harness';
import type { PlaceCard } from '../src/types/place';
const plan: DiningPlan = { id: 'p', title: 'Dinner', status: 'active', completedAt: null, createdAt: '2026-01-01', updatedAt: '2026-01-02', placeIds: [] };
const place = (id: string, status: PlaceCard['status'] = 'want_to_go'): PlaceCard => ({ id, placeName: 'Café & 麵', address: '1 Test / Road', areaCity: 'Town', category: 'cafe', tags: ['Coffee'], sources: [], status, isFavorite: false, createdAt: '2026-01-01', updatedAt: '2026-01-01', sourceInstagramUrl: 'https://www.instagram.com/p/test/' });
test('plan title validates trimmed Unicode code points', () => { assert.equal(normalizePlanTitle('  Dinner \n'), 'Dinner'); assert.equal(normalizePlanTitle('😀'.repeat(80)).length, 160); for (const s of ['  ', '😀'.repeat(81)])
    assert.throws(() => normalizePlanTitle(s)); });
test('plan transitions and stable ordering preserve membership and input', () => { assert.deepEqual(planTransition('completed', 'now'), { status: 'completed', completedAt: 'now' }); assert.deepEqual(planTransition('active', 'now'), { status: 'active', completedAt: null }); const input = [{ ...plan, id: 'z' }, { ...plan, id: 'a' }, { ...plan, id: 'done', status: 'completed' as const, completedAt: '2027' }]; assert.deepEqual(sortPlans(input).map(p => p.id), ['a', 'z', 'done']); assert.equal(input[0].id, 'z'); });
test('membership duplicates, capacity, and deleted library records', () => { const p = { ...plan, placeIds: Array.from({ length: 20 }, (_, i) => String(i)) }; assert.match(membershipFeedback(p, '0')!, /Already/); assert.match(membershipFeedback(p, '21')!, /full/); assert.equal(membershipFeedback(plan, '0'), null); assert.deepEqual(planPlaces(p, [place('0'), place('8')]).map(p => p.id), ['0', '8']); });
test('picker handles empty, one, skipped, explicit inclusion and injected boundaries without mutation', () => { assert.equal(pickPlanPlace([]), null); const skipped = place('s', 'skipped'); assert.equal(pickPlanPlace([skipped]), null); assert.equal(pickPlanPlace([skipped], true, () => { throw Error('no random needed'); }), skipped); const values = [place('a'), skipped, place('b', 'visited')]; for (const n of [0, -1, NaN])
    assert.equal(pickPlanPlace(values, false, () => n)?.id, 'a'); for (const n of [1, 2, 1 - Number.EPSILON])
    assert.equal(pickPlanPlace(values, false, () => n)?.id, 'b'); assert.equal(values.length, 3); });
test('Maps URLs encode Unicode and prefer precise Place IDs with no origin', () => { for (const action of ['map', 'directions'] as const) {
    const url = new URL(buildMapUrl({ ...place('x'), placeId: 'ChIJ /&' }, action)!);
    assert.equal(url.searchParams.get('api'), '1');
    assert.equal(url.searchParams.get(action === 'map' ? 'query' : 'destination'), 'Café & 麵, 1 Test / Road');
    assert.equal(url.searchParams.get(action === 'map' ? 'query_place_id' : 'destination_place_id'), 'ChIJ /&');
    assert.equal(url.searchParams.has('origin'), false);
} });
test('Maps fallbacks reject unsafe URLs and enforce length limits', () => { for (const s of ['javascript:alert(1)', 'https://google.com.evil/maps', 'https://evil@www.google.com/maps', 'http://maps.google.com/'])
    assert.equal(validStoredMapUrl(s), null); const p = { ...place('x'), mapUrl: 'https://maps.app.goo.gl/test' }; assert.equal(buildMapUrl(p, 'map'), p.mapUrl); assert.match(buildMapUrl(p, 'directions')!, /destination=/); assert.equal(buildMapUrl({ ...p, placeName: '', address: '', mapUrl: undefined }, 'map'), null); assert.equal(buildMapUrl({ ...p, placeId: 'id', address: '界'.repeat(2048) }, 'map'), null); const old = 'https://www.google.com/maps/dir/?api=1&origin=old&origin_place_id=x&destination=food'; assert.equal(new URL(buildMapUrl({ ...p, mapUrl: old }, 'directions')!).searchParams.has('origin'), false); });
test('repository maps nested rows to ordered domain IDs without exposing ownership', () => { const row = { id: 'p', title: 'Dinner', status: 'active' as const, completed_at: null, created_at: 'a', updated_at: 'b', user_id: 'secret', dining_plan_items: [{ id: 'z', saved_place_id: '2', created_at: 'a' }, { id: 'a', saved_place_id: '1', created_at: 'a' }] }; const mapped = mapPlanRow(row); assert.deepEqual(mapped.placeIds, ['1', '2']); assert.ok(!('user_id' in mapped)); });
test('schema 4 exports plans separately and preserves existing saved-place data', () => { const p = { ...plan, placeIds: ['a', 'b'] }; const data = createPlaceDataExport([place('a')], [], 'now', [], [p]); assert.equal(data.schemaVersion, 4); assert.deepEqual(data.data.diningPlans, [p]); assert.equal(data.data.savedPlaces[0].id, 'a'); assert.ok(!('savedPlaces' in data.data.diningPlans[0])); });
test('plan state preserves confirmed rows on write failure and permits retry', async () => { const h = hooks(); let fail = true; let rows = [plan]; const repo = { list: async () => rows }; const { usePlansState } = load('src/store/plans-context.tsx', { react: h.react, '../config/backend': { backendConfig: {} }, '../observability/error-monitoring': { errorMonitoring: { captureException() { } } } }); const render = () => h.render(() => usePlansState(repo)); render(); await tick(); assert.equal(render().plans.length, 1); const action = async () => { if (fail)
    throw new PlanStorageError('Offline'); rows = [{ ...plan, title: 'Changed' }]; }; assert.equal(await render().mutate(action), false); assert.equal(render().plans[0].title, 'Dinner'); assert.ok(render().error); fail = false; assert.equal(await render().mutate(action), true); assert.equal(render().plans[0].title, 'Changed'); assert.equal(render().error, undefined); });
test('plan refresh failure retains confirmed state and cannot overwrite newer refresh', async () => { const h = hooks(); let deferred: any; let fail = false; const repo = { list: async (): Promise<DiningPlan[]> => { if (fail)
        throw Error(); return [plan]; } }; const { usePlansState } = load('src/store/plans-context.tsx', { react: h.react, '../config/backend': { backendConfig: {} }, '../observability/error-monitoring': { errorMonitoring: { captureException() { } } } }); const render = () => h.render(() => usePlansState(repo)); render(); await tick(); fail = true; await render().refresh(); assert.equal(render().plans.length, 1); fail = false; repo.list = () => new Promise(r => { deferred = r; }); const stale = render().refresh(); repo.list = async () => [{ ...plan, title: 'New' }]; await render().refresh(); deferred([plan]); await stale; assert.equal(render().plans[0].title, 'New'); });
test('old account reads and mutations cannot hydrate the next account', async () => { const h = hooks(); let finish: any; const first = { list: async () => [plan] }; const second = { list: async () => [{ ...plan, id: 'other' }] }; let repo = first; const { usePlansState } = load('src/store/plans-context.tsx', { react: h.react, '../config/backend': { backendConfig: {} }, '../observability/error-monitoring': { errorMonitoring: { captureException() { } } } }); const render = () => h.render(() => usePlansState(repo)); render(); await tick(); const pending = render().mutate(() => new Promise(r => { finish = r; })); repo = second; render(); await tick(); finish(); assert.equal(await pending, false); assert.equal(render().plans[0].id, 'other'); });
test('plan repository provides duplicate/capacity feedback and retries with stable identity', async () => { let code: string | undefined; const calls: any[] = []; const client = { from: (table: string) => ({ insert: async (value: object) => { calls.push([table, value]); return { error: code ? { code } : null }; }, upsert: (value: object) => { calls.push([table, value]); return { select: async () => ({ data: [{ id: 'stable' }], error: null }) }; } }) }; const repo = new PlansRepository(client as any, 'owner'); for (const [c, message] of [['23505', /Already/], ['P0020', /full/]] as const) {
    code = c;
    await assert.rejects(repo.add('plan', 'place'), message);
} await repo.create(' Dinner ', 'stable'); await repo.create(' Dinner ', 'stable'); assert.equal(calls[2][1].id, calls[3][1].id); });
test('plan analytics contain only fixed action values', () => { const events: any[] = []; const { analytics } = load('src/observability/analytics.ts', { 'expo-application': {}, 'expo-constants': {}, 'react-native': rn, 'posthog-react-native': { PostHog: class {
            capture(...args: any[]) { events.push(args); }
        } } }); analytics.planAction('created'); analytics.mapHandoffOpened('directions'); assert.deepEqual(events.map(e => e[0]), ['plan_action', 'map_handoff_opened']); for (const e of events) {
    assert.deepEqual(Object.keys(e[1]).sort(), ['action', 'app_build', 'app_version', 'environment', 'platform']);
} });
test('plan screen creates, adds, picks, completes and confirms deletion through user controls', async () => {
    const h = hooks();
    const calls: string[] = [];
    const alerts: any[] = [];
    let selected: string | undefined;
    const state = { plans: [{ ...plan, placeIds: ['a', 's'] }], loading: false, busy: false, error: undefined, refresh: async () => { }, mutate: async (action: any) => { await action({ create: async () => calls.push('create'), update: async () => calls.push('update'), add: async () => calls.push('add'), remove: async () => calls.push('delete'), removePlace: async () => calls.push('remove') }); return true; } };
    const { PlansScreen } = load('src/screens/plans-screen.tsx', { react: h.react, 'expo-router': { useFocusEffect: () => { } }, 'react-native': { ...rn, Keyboard: { isVisible: () => false, dismiss() { } }, BackHandler: { addEventListener: () => ({ remove() { } }) }, Alert: { alert: (...a: any[]) => alerts.push(a) } }, 'react-native-safe-area-context': { SafeAreaView: 'SafeArea' }, '../store/plans-context': { usePlans: () => state }, '../store/PlacesContext': { usePlaces: () => ({ places: [place('a'), place('s', 'skipped'), place('b')], retryStorage() { } }) }, '../design-system/theme': { useAppTheme: () => ({ theme }) }, '../components/v2-controls': { V2Button: 'Button', V2TextField: 'Field' }, '../components/v2-layout': { V2TopBar: 'Top', V2SectionLabel: 'Label' }, '../components/map-buttons': { MapButtons: 'Maps' }, '../observability/analytics': { analytics: { planAction() { } } } });
    const navigation = { navigate: (r: any) => calls.push(r.name), goBack: () => calls.push('back') };
    const render = () => h.render(() => PlansScreen({ navigation, planId: selected }));
    const button = (label: string) => flatten(render()).find(n => n.type === 'Button' && n.props.label === label);
    button('Create plan').props.onPress();
    flatten(render()).find(n => n.type === 'Field').props.onChangeText('Meal');
    await button('Save title').props.onPress();
    await tick();
    assert.ok(calls.includes('create'));
    selected = 'p';
    render();
    render();
    button('Pick for me').props.onPress();
    assert.ok(flatten(render()).some(n => String(n.props?.children).includes('Only eligible place: ')));
    await button('Complete plan').props.onPress();
    await tick();
    assert.ok(calls.includes('update'));
    button('Add saved places').props.onPress();
    await button('Add Café & 麵').props.onPress();
    await tick();
    assert.ok(calls.includes('add'));
    button('Delete plan').props.onPress();
    assert.ok(!calls.includes('delete'));
    await alerts.at(-1)[2][1].onPress();
    await tick();
    assert.ok(calls.includes('delete'));
});
function planScreenFixture(initial:DiningPlan[], addPlaceId?:string) {
 const h=hooks(),alerts:any[]=[],calls:string[]=[];let keyboard=false;let hardwareBack=()=>false;let fail=false;
 const state={plans:initial,loading:false,busy:false,error:undefined as string|undefined,refresh:async()=>{},mutate:async(action:any)=>{if(fail)return false;await action({create:async()=>calls.push('create'),add:async()=>calls.push('add'),update:async()=>calls.push('update')});return true;}};
 const {PlansScreen}=load('src/screens/plans-screen.tsx',{react:h.react,'expo-router':{useFocusEffect:(fn:any)=>fn()},'react-native':{...rn,Keyboard:{isVisible:()=>keyboard,dismiss:()=>{keyboard=false;calls.push('keyboard');}},BackHandler:{addEventListener:(_:string,fn:any)=>{hardwareBack=fn;return {remove(){}};}},Alert:{alert:(...args:any[])=>alerts.push(args)}},'react-native-safe-area-context':{SafeAreaView:'Safe'},'../store/plans-context':{usePlans:()=>state},'../store/PlacesContext':{usePlaces:()=>({places:[place('a'),place('s','skipped')],retryStorage(){}})},'../design-system/theme':{useAppTheme:()=>({theme})},'../components/v2-controls':{V2Button:'Button',V2TextField:'Field'},'../components/v2-layout':{V2TopBar:'Top',V2SectionLabel:'Label'},'../components/map-buttons':{MapButtons:'Maps'},'../observability/analytics':{analytics:{planAction(){}}}});
 const render=(id?:string)=>h.render(()=>PlansScreen({navigation:{navigate(){},goBack:()=>calls.push('back')},planId:id,addPlaceId}));
 return {state,calls,alerts,render,back:()=>hardwareBack(),keyboard:()=>{keyboard=true;},fail:(value:boolean)=>{fail=value;}};
}
test('add-from-place exposes duplicate and full feedback without a database attempt',async()=>{const f=planScreenFixture([{...plan,id:'duplicate',placeIds:['a']},{...plan,id:'full',placeIds:Array.from({length:20},(_,i)=>String(i))},{...plan,id:'empty'}],'a');f.render();const nodes=flatten(f.render());for(const label of ['Already in this plan.','This plan is full (20 places).'])assert.ok(nodes.find(n=>n.props?.label===label)?.props.disabled);nodes.find(n=>n.props?.label==='Add to this plan').props.onPress();await tick();assert.deepEqual(f.calls,['add']);});
test('plan picker explains empty and all-skipped states and allows explicit inclusion',()=>{const f=planScreenFixture([{...plan,placeIds:[]}]);f.render('p');const click=(label:string)=>flatten(f.render('p')).find(n=>n.props?.label===label).props.onPress();click('Pick for me');assert.ok(flatten(f.render('p')).some(n=>String(n.props?.children).includes('Add places to your shortlist first')));f.state.plans=[{...plan,placeIds:['s']}];click('Pick for me');assert.ok(flatten(f.render('p')).some(n=>String(n.props?.children).includes('All places are skipped')));click('Include skipped places');click('Pick for me');assert.ok(flatten(f.render('p')).some(n=>n.props?.label==='Open picked place'));click('Dismiss result');assert.ok(!flatten(f.render('p')).some(n=>n.props?.label==='Open picked place'));});
test('title failure retains intent and Back dismisses keyboard before discard confirmation',async()=>{const f=planScreenFixture([]);f.render();flatten(f.render()).find(n=>n.props?.label==='Create plan').props.onPress();flatten(f.render()).find(n=>n.type==='Field').props.onChangeText('Draft');f.fail(true);flatten(f.render()).find(n=>n.props?.label==='Save title').props.onPress();await tick();assert.equal(flatten(f.render()).find(n=>n.type==='Field').props.value,'Draft');f.keyboard();f.back();assert.deepEqual(f.calls,['keyboard']);assert.equal(f.alerts.length,0);f.back();assert.equal(f.alerts.at(-1)[0],'Discard title changes?');assert.ok(!f.calls.includes('back'));f.fail(false);flatten(f.render()).find(n=>n.props?.label==='Save title').props.onPress();await tick();assert.ok(f.calls.includes('create'));});
test('Maps controls report successful opens only and offer retry after device failure',async()=>{const opened:string[]=[];const events:string[]=[];const alerts:any[]=[];let fail=true;const {MapButtons}=load('src/components/map-buttons.tsx',{'react-native':{Linking:{openURL:async(url:string)=>{if(fail)throw Error('unavailable');opened.push(url);}},Alert:{alert:(...a:any[])=>alerts.push(a)}},'./v2-controls':{V2Button:'Button'},'../observability/analytics':{analytics:{mapHandoffOpened:(action:string)=>events.push(action)}}});const buttons=flatten(MapButtons({place:place('a')})).filter(n=>n.type==='Button');buttons[1].props.onPress();await tick();assert.equal(alerts.length,1);assert.equal(events.length,0);fail=false;buttons[1].props.onPress();await tick();assert.equal(events[0],'directions');assert.ok(opened[0].includes('/dir/'));});
test('Sentry scrubs plan content and database response context',()=>{const {scrubSentryEvent}=load('src/observability/error-monitoring.ts',{'expo-application':{},'expo-constants':{},'react-native':rn,'@sentry/react-native':{}});const result=scrubSentryEvent({message:'private title',extra:{plan:'secret'},contexts:{planId:'private-id',title:'private-title',response:{id:'private-row'}},exception:{values:[{value:'database private data'}]}});const json=JSON.stringify(result);for(const secret of ['private title','private-id','private-title','private-row','database private data'])assert.ok(!json.includes(secret));});
test('plan token provider rejects a switched Clerk subject before database access',async()=>{const h=hooks();let options:any;const {PlansProvider}=load('src/store/plans-context.tsx',{react:h.react,'@supabase/supabase-js':{createClient:(_:any,__:any,o:any)=>{options=o;return {};}},'../config/backend':{backendConfig:{supabaseUrl:'https://test.invalid',supabasePublishableKey:'test'}},'../repositories/plans/plans-repository':{PlansRepository:class{async list(){return [];}},PlanStorageError},'../observability/error-monitoring':{errorMonitoring:{captureException(){}}}});const token='x.'+Buffer.from(JSON.stringify({sub:'other'})).toString('base64url')+'.x';h.render(()=>PlansProvider({userId:'owner',accessTokenProvider:async()=>token,children:null}));await assert.rejects(options.accessToken(),/Account changed/);h.unmount();});
