// Public configuration only. Generated by node script/build-sharing-web.mjs.
export const endpoint = "https://mrlumqsdabxptkwmqjwf.supabase.co/functions/v1/shared-plan";
export const nativeScheme = "";
